version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/authservice:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/userservice:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  questiongenerator:
    container_name: questiongenerator-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/questiongenerator:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./questiongenerator
    depends_on:
      - mongodb
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  gamehistoryservice:
    container_name: gamehistoryservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/gamehistoryservice:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./gamehistoryservice
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  perfilservice:
    container_name: perfilservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/perfilservice/perfil-api:latest
    profiles: ["dev", "prod"]
    build: ./perfilservice
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  alluserservice:
    container_name: alluserservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/apis/alluserservice/allusers-api:latest
    profiles: ["dev", "prod"]
    build: ./apis/alluserservice
    depends_on:
      - mongodb
    ports:
      - "8006:8006"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
  
  allquestionservice:
    container_name: allquestionservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/apis/allquestionservice/allquestions-api:latest
    profiles: ["dev", "prod"]
    build: ./apis/allquestionservice
    depends_on:
      - mongodb
    ports:
      - "8007:8007"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
  
  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/gatewayservice:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - questiongenerator
      - perfilservice
      - gamehistoryservice
      - alluserservice
      - allquestionservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      GAMEHISTORY_SERVICE_URL: http://gamehistoryservice:8004
      GENERATOR_SERVICE_URL: http://questiongenerator:8003
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      PERFIL_SERVICE_URL: http://perfilservice:8005
      ALLUSERS_SERVICE_URL: http://alluserservice:8006
      ALLQUESTIONS_SERVICE_URL: http://allquestionservice:8007

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es2c/webapp:latest
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    build: ./webapp
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000" 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
