ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Restricciones de arquitectura


[role="arc42help"]
****
.Contenido
Cualquier requisito que limite a los arquitectos de software en su libertad de diseño e implementación de decisiones o decisiones sobre el proceso de desarrollo. Estas limitaciones a veces van más allá de los sistemas individuales y son válidas para organizaciones y empresas enteras.

.Motivación
Los arquitectos deben saber exactamente dónde tienen libertad en sus decisiones de diseño y dónde deben cumplir restricciones.
Siempre hay que abordar las limitaciones; Sin embargo, pueden ser negociables.

.Forma
Tablas simples de restricciones con explicaciones.
Si es necesario, puedes subdividirlos en
limitaciones técnicas, limitaciones organizativas y políticas y
convenciones (por ejemplo, pautas de programación o control de versiones, documentación o convenciones de nomenclatura)


.Más información

Consulte https://docs.arc42.org/section-2/[Architecture Restriints] en la documentación de arc42.

****

.Restricciones técnicas
[options="header",cols="1,1"]
|===
|Restricción|Explicación
| Docker | El proyecto de desplegará en un Host Docker.
| Tecnología | Se empleará React.
| Documentación | Se usará la plantilla Arc42.
| Base de datos |  Se empleará MongoDB como base de datos por su sencillez y facilidad de uso. Además es la base de datos empleada en la base del proyecto.
| Pruebas | Cobertura, Pruebas de aceptación (e2e), Pruebas de carga
| WikiData | Se empleará WikiData para obtener la información para generar las preguntas y respuestas.
|===

.Restricciones organizativas
[options="header",cols="1,1"]
|===
|Restricción|Explicación
| Reuniones | Se realizarán reuniones semanales los lunes de 13:00 a 15:00. Estas reuniones se verán reflejadas en GitHub a través de un acta. Podrían realizarse reuniones entre semana si fuese necesario.
| GitHub Issues | Para permitir al profesorado llevar un seguimiento del trabajo en equipo se emplearán los Issues de GitHub para reflejar la asignación de tareas así como el diágolo entre semana del equipo.
| Tamaño del equipo | El equipo está formado por 5 personas.
|===

